name: Build from latest commit

on:
  #pull_request:
  #push:
  workflow_dispatch:

jobs:
  build:
    name: Test ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: mips_24kc
            target: ath79-generic
            runtime_test: false

          - arch: mipsel_24kc
            target: mt7621
            runtime_test: false

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Determine branch name
        run: |
          #BRANCH="${GITHUB_BASE_REF#refs/heads/}"
          BRANCH="openwrt-22.03"
          echo "Building for $BRANCH"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Determine changed packages
        run: |
          # only detect packages with changes
          #PKG_ROOTS=$(find . -name Makefile | \
          #  grep -v ".*/src/Makefile" | \
          #  sed -e 's@./\(.*\)/Makefile@\1/@')
          #CHANGES=$(git diff --diff-filter=d --name-only origin/$BRANCH...)

          #for ROOT in $PKG_ROOTS; do
          #  for CHANGE in $CHANGES; do
          #    if [[ "$CHANGE" == "$ROOT"* ]]; then
          #      PACKAGES+=$(echo "$ROOT" | sed -e 's@.*/\(.*\)/@\1 @')
           #     break
          #    fi
          #  done
          #done

          # fallback to test packages if nothing explicitly changes this is
          # should run if other mechanics in packages.git changed
          #PACKAGES="${PACKAGES:-vim attendedsysupgrade-common bmon}"
          #PACKAGES="chrony dawn udpxy unbound"
          PACKAGES="unbound"
          OWNER="NLnetLabs"

          echo "Building $PACKAGES"
          echo "PACKAGES=$PACKAGES" >> $GITHUB_ENV
          echo "OWNER=$OWNER" >> $GITHUB_ENV

      - name: Get latest commit SHA for $PACKAGES and Prepare Release Notes
        shell: bash
        run: |
          DATE_PKG=$(curl -sSL https://api.github.com/repos/$OWNER/$PACKAGES/commits/master \
           | tr -d "\"" |grep "date:" | tail -1 | sed "s/\"//g" | awk -F": " '{print $2}' | tr -d TZ":" | rev | cut -c 7- | rev \
          )
          SHA_PKG=$(curl -sSL https://api.github.com/repos/$OWNER/$PACKAGES/commits/master \
           | jq -r '.sha' \
           #| grep "sha\":" | head -1 | tr -d "sha"":"","" ""\"" \
          )
          TPKG=$(curl -sSL https://api.github.com/repos/$OWNER/$PACKAGES/commits/master \
           | grep "sha\":" | head -1 | tr -d "sha"":"","" ""\"" \
          )
          #$SHA_pkg = (curl -sSL https://api.github.com/repos/$OWNER/$PACKAGES/commits/master | jq -r '.sha')
          #echo "https://github.com/$OWNER/$PACKAGES/commits/$SHA_PKG" >> "${{ github.workspace }}-nightly_builds_release_notes.txt"
          #find ./net/unbound -iname Makefile
          echo "DATE_PKG $DATE_PKG SHA_PKG $SHA_PKG TPKG $TPKG"
          echo "SHA_PKG=$SHA_PKG" >> $GITHUB_ENV
          echo "DATE_PKG=$DATE_PKG" >> $GITHUB_ENV
          echo "-----"
          echo "$GITHUB_ENV"
          
      - name: Generate build keys
        run: |
          sudo apt-get update
          sudo apt-get install -y signify-openbsd
          signify-openbsd -G -n -c 'DO NOT USE - OpenWrt packages feed CI' -p packages_ci.pub -s packages_ci.sec
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "KEY_BUILD<<$EOF" >> $GITHUB_ENV
          cat packages_ci.sec >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Update Makefile
        if: matrix.arch != 'linux_x86_64'
        run: |
          #cd ./net/unbound/
          #sed -i "s/PKG_SOURCE_DATE:=.*/PKG_SOURCE_DATE:=$(date +%Y-%m-%d)/" ./net/unbound/Makefile
          sed -i "s/PKG_SOURCE_DATE:=.*/PKG_SOURCE_DATE:=$DATE_PKG/" ./net/unbound/Makefile
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$SHA_PKG/" ./net/unbound/Makefile
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=skip/" ./net/unbound/Makefile
          grep PKG_SOURCE_DATE ./net/unbound/Makefile
          grep PKG_SOURCE_VERSION ./net/unbound/Makefile
          grep PKG_MIRROR_HASH ./net/unbound/Makefile

      - name: Build
        #uses: openwrt/gh-action-sdk@v9
        uses: cmangla/gh-action-sdk@pr-hash-fixup-option
        #uses：qwerttvv/Router/@gh-action-sdk
        env:
          ARCH: ${{ matrix.arch }}-${{ env.BRANCH }}
          FEEDNAME: packages_ci
          INDEX: 1
          KEY_BUILD: ${{ env.KEY_BUILD }}
          V: s
          FIXUP: 1
          #IGNORE_PKG_HASH_ISSUE: 1
          NO_REFRESH_CHECK: true

      - name: Move created packages to project dir
        if: always()
        run: cp bin/packages/${{ matrix.arch }}/packages_ci/* . || true

      - name: Collect metadata
        if: always()
        run: |
          MERGE_ID=$(git rev-parse --short HEAD)
          echo "MERGE_ID=$MERGE_ID" >> $GITHUB_ENV
          echo "BASE_ID=$(git rev-parse --short HEAD^1)" >> $GITHUB_ENV
          echo "HEAD_ID=$(git rev-parse --short HEAD^2)" >> $GITHUB_ENV
          PRNUMBER=${GITHUB_REF_NAME%/merge}
          echo "PRNUMBER=$PRNUMBER" >> $GITHUB_ENV
          echo "ARCHIVE_NAME=${{matrix.arch}}-$PRNUMBER-$MERGE_ID" >> $GITHUB_ENV

      - name: Generate metadata
        if: always()
        run: |
          cat << _EOF_ > PKG-INFO
          Metadata-Version: 2.1
          Name: ${{env.ARCHIVE_NAME}}
          Version: $BRANCH
          Author: $GITHUB_ACTOR
          Home-page: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$PRNUMBER
          Download-URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          Summary: $PACKAGES
          Platform: ${{ matrix.arch }}

          Packages for OpenWrt $BRANCH running on ${{matrix.arch}}, built from PR $PRNUMBER
          at commit $HEAD_ID, against $BRANCH at commit $BASE_ID, with merge SHA $MERGE_ID.

          Modified packages:
          _EOF_
          for p in $PACKAGES
          do
            echo "  "$p >> PKG-INFO
          done
          echo >> PKG-INFO
          echo Full file listing: >> PKG-INFO
          ls -al *.?pk >> PKG-INFO || true
          cat PKG-INFO

      - name: zip packages
        run: |
          zip -r ${{env.ARCHIVE_NAME}}-pkgs.zip -n *.?pk
        #uses: montudor/action-zip@v1
        #with:
        #  args: zip -X -r ${{env.ARCHIVE_NAME}}-pkgs.zip . -x *exclude
          
      - name: upload packages
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARCHIVE_NAME}}-pkgs
          path: ${{env.ARCHIVE_NAME}}-pkgs.zip 

      - name: Release
        uses: ncipollo/release-action@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: "${{ github.run_number }}_${{env.ARCHIVE_NAME}}-pkgs.zip,*.?pk,Packages,Packages.*"
          allowUpdates: true
          replacesArtifacts: true
          bodyFile: "PKG-INFO"
          tag: wkflo${{ github.run_number }}_${{env.ARCHIVE_NAME}}         
      #- name: release 2
      #  uses: softprops/action-gh-release@v2
        #if: github.ref_type == 'tag'
      #  with:
       #   tag_name: ${{env.ARCHIVE_NAME}}
       #   prerelease: false
       #   draft: false
       #   generat_release_notes: false
          #name: ${{needs.changelog.output.tag}}
       #   files: 
       #     ${{env.ARCHIVE_NAME}}-pkgs.zip
       #     Packages
       #     Packages.*
       #     PKG-INFO
       # env:
       #   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
       
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 9
          keep_minimum_runs: 0
    
      - name: Remove old Releases
        uses: sgpublic/delete-release-action@v1.2
        with:
          release-drop: true
          release-keep-count: 5
          release-drop-tag: true
          pre-release-drop: true
          pre-release-keep-count: -1
          pre-release-drop-tag: true
          draft-drop: true
          draft-drop-count: -1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
      - name: Store logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARCHIVE_NAME}}-logs
          path: |
            logs/
            PKG-INFO

      - name: Remove logs
        if: always()
        run: sudo rm -rf logs/ || true

      - name: Check if any packages were built
        run: |
          if [ -n "$(find . -maxdepth 1 -type f -name '*.ipk' -print -quit)" ]; then
            echo "Found *.ipk files"
            HAVE_IPKS=true
          else
            echo "No *.ipk files found"
            HAVE_IPKS=false
          fi
          echo "HAVE_IPKS=$HAVE_IPKS" >> $GITHUB_ENV

      - name: Register QEMU
        if: ${{ matrix.runtime_test && fromJSON(env.HAVE_IPKS) }}
        run: |
          sudo docker run --rm --privileged aptman/qus -s -- -p

      - name: Build Docker container
        if: ${{ matrix.runtime_test && fromJSON(env.HAVE_IPKS) }}
        run: |
          docker build --platform linux/${{ matrix.arch }} -t test-container --build-arg ARCH .github/workflows/
        env:
          ARCH: ${{ matrix.arch }}-${{ env.BRANCH }}

      - name: Test via Docker container
        if: ${{ matrix.runtime_test && fromJSON(env.HAVE_IPKS) }}
        run: |
          docker run --platform linux/${{ matrix.arch }} --rm -v $GITHUB_WORKSPACE:/ci test-container
